### ISSUE TITLE
drawTxt

### ISSUE THREAD

**Issue by outsider31000** [CallMeNC/vorp_sellhorse#1]
drawTxt(v.pressToSell, 0.5, 0.9, 0.7, 0.7, 255, 255, 255, 255, true, true)

arent you missing a function?
![Screenshot 2022-01-31 192731](https://user-images.githubusercontent.com/87246847/151859798-ba33e942-bb40-4690-ad2f-c63a07b4f450.jpg)

**Comment by Or1ginaI** [comment]
Updated main.lua with drawTxt function. Issue resolved, closing
