### ISSUE TITLE
selling horse returns nil

### ISSUE THREAD

**Issue by istoking** [CallMeNC/vorp_sellhorse#3]
I've added the resource as is, without any edits, since it didn't need anything changed in the config. When trying to sell any horse, I always get nil returned on screen. Am I supposed to own the horse in order to sell? (update: tried selling an owned horse, same issue; NIL)

![20220928171734_1](https://user-images.githubusercontent.com/58592678/192686560-ea844cdf-2b8c-4f76-b199-8e466c84d6cc.jpg)

**Comment by Or1ginaI** [comment]
Howdy istoking! Please repeat the actions you did to get the error and send a screenshot of the F8 console, specifically where it refers to the script. That’ll give me more context on what caused the error.

**Comment by istoking** [comment]
> Howdy istoking! Please repeat the actions you did to get the error and send a screenshot of the F8 console, specifically where it refers to the script. That’ll give me more context on what caused the error.

Hi, there was no error on console. There was only the output of 'nil' on the right side of my screen, as shown in the screenshot. 

![20220929201853_1](https://user-images.githubusercontent.com/58592678/192966025-28011c2b-2533-419a-b963-6578415e42af.jpg)

**Comment by Or1ginaI** [comment]
I think I found our issue! Line 128 of client refers to a key value pair that was not properly formatted. Please download the updated version of the script and try again!

**Comment by istoking** [comment]
> I think I found our issue! Line 128 of client refers to a key value pair that was not properly formatted. Please download the updated version of the script and try again!

seems to return the same thing

![Screenshot_1](https://user-images.githubusercontent.com/58592678/193436997-39deb648-0d31-40a6-89d2-d367ba714e7b.png)

![20221002164631_1](https://user-images.githubusercontent.com/58592678/193437002-f53b441a-aa24-495b-aa04-3f4daee19fab.jpg)

**Comment by Or1ginaI** [comment]
Thanks for your patience on this istoking! This is the unfortunate part about writing a script in the beginning and knowing more _now_ than what I did when I first started. 

I've updated the config.lua. Please re-download and try again. Also, this script sells _wild horses_ so you will receive a message about the horse not being wild if/when you steal one and try to sell it. I suggest going out and breaking a wild horse and taking it to the seller to try.

**Comment by istoking** [comment]
> Thanks for your patience on this istoking! This is the unfortunate part about writing a script in the beginning and knowing more _now_ than what I did when I first started.
> 
> I've updated the config.lua. Please re-download and try again. Also, this script sells _wild horses_ so you will receive a message about the horse not being wild if/when you steal one and try to sell it. I suggest going out and breaking a wild horse and taking it to the seller to try.

all good, I'll test it soon. That was one of the things I was wondering about, but couldn't see in the code where it differentiated between a stolen horse or a broken horse. Thanks for being available to work on it and fix it

**Comment by istoking** [comment]
All working as it should, thanks for the resource 👍
